production update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,7 +40,7 @@ jobs:
         run: pnpm install
 
       - name: 🔬 Lint
-        run: pnpm -r run lint || true 
+        run: pnpm -r run lint || true  # Does not interrupt execution on error
 
   publish-client:
     name: 🚀 Publish Client
@@ -93,12 +93,10 @@ jobs:
     needs: [lint]
     runs-on: ubuntu-latest
     env:
+      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
       CLOUDFLARE_D1_TOKEN: ${{ secrets.CLOUDFLARE_D1_TOKEN }}
       CLOUDFLARE_DATABASE_ID: ${{ secrets.CLOUDFLARE_DATABASE_ID }}
-      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-      JWT_SECRET: ${{ secrets.JWT_SECRET }}
-      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
-      NODE_ENV: production
     steps:
       - name: ⬇️ Checkout repo
         uses: actions/checkout@v4
@@ -114,19 +112,21 @@ jobs:
         with:
           node-version: 22.9.0
 
-      - name: 📥 Install deps
-        working-directory: ./server
-        run: pnpm install
+      - name: Logs before installation
+        run: |
+          node -v
+          pnpm -v
+          which esbuild || echo "esbuild not found"
 
-      - name: ➕ Create .env file
+      - name: 📥 Install dependencies
         working-directory: ./server
         run: |
-          echo "CLOUDFLARE_D1_TOKEN=${{ secrets.CLOUDFLARE_D1_TOKEN }}" >> .env
-          echo "CLOUDFLARE_DATABASE_ID=${{ secrets.CLOUDFLARE_DATABASE_ID }}" >> .env
-          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> .env
-          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
-          echo "REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}" >> .env
-          echo "NODE_ENV=production" >> .env
+          pnpm store prune
+          pnpm install
+
+      - name: Check esbuild
+        working-directory: ./server
+        run: pnpm exec esbuild --version || echo "esbuild not found"
 
       - name: ⚙️ Build Server
         working-directory: ./server
